// Generated by Haxe 3.4.7
(function () { "use strict";
var Grid = function() {
	this.fields = [];
	this.fields = [123,123];
};
Grid.prototype = {
	get_width: function() {
		return this.fields.length;
	}
	,get_height: function() {
		return this.fields.length;
	}
};
var Main = function() { };
Main.main = function() {
	window.onload = Main.init;
};
Main.init = function() {
	Main.canvas = window.document.createElement("canvas");
	window.document.body.appendChild(Main.canvas);
	Main.context = Main.canvas.getContext("2d",null);
	Main.canvas.width = window.innerWidth;
	Main.canvas.height = window.innerHeight;
	window.onresize = function() {
		Main.canvas.width = window.innerWidth;
		Main.canvas.height = window.innerHeight;
	};
	window.requestAnimationFrame(Main.drawFrame);
	console.log(new Grid().get_height());
};
Main.drawFrame = function(time) {
	Main.context.fillStyle = "black";
	Main.context.fillRect(0,0,Main.canvas.width,Main.canvas.height);
	Main.context.fillStyle = "blue";
	Main.context.fillRect(time % 1000,0,100,100);
};
Main.main();
})();
